### PR TITLE
LOOP-2955 Allow onboarding to utilize other plugins

### PR DESCRIPTION
**Pull request by darinkrauss**
- https://tidepool.atlassian.net/browse/LOOP-2955
- Move onboarding to new LoopOnboarding plugin/repo
- Update to latest service requirements for onboarding
- Update project to disable Mac Catalyst support

Note: Needs TWO reviewers.

### CODE REVIEW

**Review by rickpasetto — COMMENTED** [review]
@darinkrauss I'm confused, and please forgive me if I missed a discussion somewhere: if a lot of this onboarding UI was moved to `tidepool-org/LoopOnboarding`, how will DIY use it if `tidepool-org/LoopOnboarding` is a private repo?

**Comment by darinkrauss** [comment]
Yes. My general workflow is to keep a repo private until the initial PR is approved. Basically, just before I submit the LW PR that includes the `LoopOnboarding` repo. This also applies to the other new repos.

**Review by nhamming — APPROVED** [review]
LGTM

**Review by rickpasetto — APPROVED** [review]
LGTM 💭

**Review by ps2 — APPROVED** [review]
LGTM!

**Pull request merged**
