### PR TITLE
LOOP-1417 Capture carbohydrate creates, updates, and deletes

### PR DESCRIPTION
**Pull request by darinkrauss**
- https://tidepool.atlassian.net/browse/LOOP-1417
- Update to use latest RemoteDataService.uploadCarbData
- Replace StoredCarbEntry and DeletedCarbEntry with SyncCarbObject

This PR is based upon changes to LoopKit in PR https://github.com/tidepool-org/LoopKit/pull/217.

Reviewers requested: 2

### CODE REVIEW

**Review by novalegra — APPROVED** [review]
LGTM!

**Review by nhamming — APPROVED** [review]
LGTM

**Review by ps2 — APPROVED** [review]
LGTM!

**Review by rickpasetto — APPROVED** [review]
LGTM 🍫

**Pull request merged**
