### PR TITLE
[LOOP-1125] Upload pump data

### PR DESCRIPTION
**Pull request by darinkrauss**
- https://tidepool.atlassian.net/browse/LOOP-1125
- https://tidepool.atlassian.net/browse/LOOP-1124
- https://tidepool.atlassian.net/browse/LOOP-3889
- Combine dose and pump event data for upload
- Fix warning

### CODE REVIEW

**Review by nhamming — APPROVED** [review]
LGTM

**Comment by darinkrauss** [comment]
LW PR for build: https://github.com/tidepool-org/LoopWorkspace/pull/741

**Review by rickpasetto — APPROVED** [review]
LGTM

**Comment by ps2** [comment]
Will review this once it is updated with the LoopKit changes (that I just reviewed).

**Comment by darinkrauss** [comment]
Replaced by https://github.com/tidepool-org/NightscoutService/pull/31.

**Pull request closed without merging**
