### PR TITLE
LOOP-1417 Capture carbohydrate entries

### PR DESCRIPTION
**Pull request by darinkrauss**
- https://tidepool.atlassian.net/browse/LOOP-1417
- Update remote data service to remove DeletedCarbEntry

### CODE REVIEW

**Comment by darinkrauss** [comment]
Related LoopWorkspace PR: https://github.com/tidepool-org/LoopWorkspace/pull/176

**Comment by rickpasetto** [comment]
@darinkrauss I'm going to have to defer to @ps2 or @novalegra who probably have more experience with Nightscout than me.

**Review by novalegra — APPROVED** [review]
LGTM!

**Review by ps2 — APPROVED** [review]
LGTM!

**Review by rickpasetto — APPROVED** [review]

**Comment by darinkrauss** [comment]
Deprecated by upcoming PR due to entirely new implementation based upon PR feedback.

**Pull request closed without merging**
